# variables in header
request_id:
  description: |
    A unique ID for tracking service request. The request ID associated
    with the request by default appears in the service logs.
  in: header
  required: true
  type: UUID

# variables in path
checkpoint_id_1:
  description: |
    The UUID of a checkpoint.
  in: path
  required: true
  type: UUID
protectable_type_1:
  description: |
    The name of a specified protectable type.
  in: path
  required: true
  type: string
provider_id_1:
  description: |
    The UUID of a provider.
  in: path
  required: true
  type: UUID
resource_id:
  description: |
    The UUID of a resource.
  in: path
  required: true
  type: UUID
tenant_id:
  description: |
    The UUID of the tenant in a multi-tenancy cloud.
  in: path
  required: true
  type: string


# variables in query


# variables in body
checkpoint:
  description: |
    A ``checkpoint`` object.
  in: body
  required: true
  type: object
checkpoint_id:
  description: |
    The UUID of the checkpoint.
  in: body
  required: true
  type: UUID
checkpoint_list:
  description: |
    The list of ``checkpoint`` objects.
  in: body
  required: true
  type: array
checkpoint_status:
  description: |
    The status of checkpoint. A valid value is ``error``, ``protecting``,
    ``available``, ``deleting``, ``deleted`` or ``error-deleting``.
  in: body
  required: true
  type: string
dependent_resources:
  description: |
    All dependent resources for a given protectable instance, It can be an
    empty list.
  in: body
  required: true
  type: array
dependent_types:
  description: |
    All dependent protectable type, It can be an empty list.
  in: body
  required: true
  type: array
description:
  description: |
    The description for this object, resource, operation and so on. May be
    ``NULL``.
  in: body
  required: true
  type: string
links:
  description: |
    Links for transfer.
  in: body
  required: true
  type: array
plan:
  description: |
    A ``plan`` object.
  in: body
  required: true
  type: object
plan_id:
  description: |
    The UUID of the plan.
  in: body
  required: true
  type: UUID
plan_list:
  description: |
    The list of ``plan`` objects.
  in: body
  required: true
  type: array
plan_name:
  description: |
    The name of the plan.
  in: body
  required: true
  type: string
plan_name_1:
  description: |
    The name of the plan.
  in: body
  required: false
  type: string
plan_parameters:
  description: |
    The specified parameters for plan.
  in: body
  required: true
  type: dict
plan_status:
  description: |
    The status of plan. A valid value is ``started`` or ``suspended``.
  in: body
  required: true
  type: string
plan_status_1:
  description: |
    The status of plan. A valid value is ``started`` or ``suspended``.
  in: body
  required: false
  type: string
protectable_instance:
  description: |
    A ``protectable_instance`` object.
  in: body
  required: true
  type: object
protectable_instance_id:
  description: |
    The UUID of a protectable instance.
  in: body
  required: true
  type: UUID
protectable_instance_list:
  description: |
    The list of ``protectable_instance`` objects.
  in: body
  required: true
  type: array
protectable_instance_name:
  description: |
    The name of a protectable instance.
  in: body
  required: true
  type: string
protectable_name:
  description: |
    The name of the protectable type.
  in: body
  required: true
  type: string
protectable_type:
  description: |
    All the available protection types.
  in: body
  required: true
  type: array
protectable_type_2:
  description: |
    A ``protectable_type`` object.
  in: body
  required: true
  type: object
protectable_type_3:
  description: |
    The name of a specified protectable type.
  in: body
  required: true
  type: string
provider:
  description: |
    A ``provider`` object.
  in: body
  required: true
  type: object
provider_id:
  description: |
    The UUID of the provider.
  in: body
  required: true
  type: UUID
provider_list:
  description: |
    The list of ``provider`` objects.
  in: body
  required: true
  type: array
provider_name:
  description: |
    The name of the provider.
  in: body
  required: true
  type: string
resource_graph:
  description: |
    The resource graph of protection plan corresponding to the checkpoint.
  in: body
  required: true
  type: array
resources:
  description: |
    The list of all resources in plan.
  in: body
  required: true
  type: array
resources_1:
  description: |
    The list of all resources in plan.
  in: body
  required: false
  type: array
schema_extended_info:
  description: |
    The extended info schema for provider.
  in: body
  required: true
  type: dict
schema_restore:
  description: |
    The restore schema for provider.
  in: body
  required: true
  type: dict
schema_saved_info:
  description: |
    The saved info schema for provider.
  in: body
  required: true
  type: dict
tenant_id_1:
  description: |
    The UUID of the tenant in a multi-tenancy cloud.
  in: body
  required: true
  type: string
