# variables in header
request_id:
  description: |
    A unique ID for tracking service request. The request ID associated
    with the request by default appears in the service logs.
  in: header
  required: true
  type: UUID

# variables in path
checkpoint_id_1:
  description: |
    The UUID of a checkpoint.
  in: path
  required: true
  type: UUID
provider_id_1:
  description: |
    The UUID of a provider.
  in: path
  required: true
  type: UUID
tenant_id:
  description: |
    The UUID of the tenant in a multi-tenancy cloud.
  in: path
  required: true
  type: string


# variables in query


# variables in body
checkpoint:
  description: |
    A ``checkpoint`` object.
  in: body
  required: true
  type: object
checkpoint_id:
  description: |
    The UUID of the checkpoint.
  in: body
  required: true
  type: UUID
checkpoint_list:
  description: |
    The list of ``checkpoint`` objects.
  in: body
  required: true
  type: array
checkpoint_status:
  description: |
    The status of checkpoint. A valid value is ``error``, ``protecting``,
    ``available``, ``deleting``, ``deleted`` or ``error-deleting``.
  in: body
  required: true
  type: string
links:
  description: |
    Links for transfer.
  in: body
  required: true
  type: array
plan:
  description: |
    A ``plan`` object.
  in: body
  required: true
  type: object
plan_id:
  description: |
    The UUID of the plan.
  in: body
  required: true
  type: UUID
plan_list:
  description: |
    The list of ``plan`` objects.
  in: body
  required: true
  type: array
plan_name:
  description: |
    The name of the plan.
  in: body
  required: true
  type: string
plan_name_1:
  description: |
    The name of the plan.
  in: body
  required: false
  type: string
plan_parameters:
  description: |
    The specified parameters for plan.
  in: body
  required: true
  type: dict
plan_status:
  description: |
    The status of plan. A valid value is ``started`` or ``suspended``.
  in: body
  required: true
  type: string
plan_status_1:
  description: |
    The status of plan. A valid value is ``started`` or ``suspended``.
  in: body
  required: false
  type: string
provider_id:
  description: |
    The UUID of the provider.
  in: body
  required: true
  type: UUID
resource_graph:
  description: |
    The resource graph of protection plan corresponding to the checkpoint.
  in: body
  required: true
  type: array
resources:
  description: |
    The list of all resources in plan.
  in: body
  required: true
  type: array
resources_1:
  description: |
    The list of all resources in plan.
  in: body
  required: false
  type: array
tenant_id_1:
  description: |
    The UUID of the tenant in a multi-tenancy cloud.
  in: body
  required: true
  type: string
